all:
  hosts:
    switch1:
      ansible_host: 192.168.253.120
      ansible_user: admin
      ansible_password: StrongPassword123
      ansible_network_os: cisco.ios.ios
    switch2:
      ansible_host: 192.168.253.121
      ansible_user: admin
      ansible_password: StrongPassword123
      ansible_network_os: cisco.ios.ios
    switch3:
      ansible_host: 192.168.253.150
      ansible_user: admin
      ansible_password: StrongPassword123 
      ansible_network_os: cisco.ios.ios
    switch4:
      ansible_host: 192.168.253.122
      ansible_user: admin
      ansible_password: StrongPassword123
      ansible_network_os: cisco.ios.ios